theory Scratch_Geodesic
  imports "Applied_Math_D34_Analytic.D34_Geodesic_Branch"
begin

text \<open>Guard-only: the geodesic (c-space normal-coordinate) branch content lives in
  \<open>Appendix/AnalyticBridge/D34_Geodesic_Branch.thy\<close>.  This file just re-checks the
  key names are present in the heap.\<close>

thm Wc_def Wc_eq_cmod_sq U_dip_Wc
thm has_derivative_pair_phase_sum_x pair_phase_sum_perp_slot_zero
thm Wc_curve_d1 Wc_curve_d2 Wc_curve_d3
thm T3rad_def T3rad_slot_perp_zero
thm Wc_slot_perp_zero T1rad_slot_perp_zero T2rad_slot_perp_zero
thm has_derivative_pair_phase_sum_c has_derivative_Wc_c
thm has_derivative_U_dip_omega_factored gradU_dip_inner_omega
thm Phi_par_radial_dictionary Phi_par_zero_radial
thm has_derivative_pair_phase_sum_c_coeff Wc_dd_def Wc_d2_eq_dd has_derivative_Wc_d1_c
thm has_derivative_Wc_d1_comp has_derivative_gradU_inner_e_hess
thm has_derivative_gradU_inner_e_factored HessU_quad_dictionary
thm H_par_eq_quadform H_par_radial_dictionary
thm Hrad2_def Hrad2_radial_form Hrad2_slot_perp_zero
thm Lambda_rad_ij_def Jac3_H12rad_def Jac3_H12rad_identity Jac3_H12rad_nonzero_criterion
thm pair_phase_sum_slot_value pair_phase_sum_slot_value_odd
thm Wc_slot_value T1rad_slot_value T2rad_slot_value T3rad_slot_value
thm Hrad2_slot_value

end
